version: '3'
services:
  client:
    env_file:
      - .env
    environment:
      - SERVER_CONNECT_URI=tcp://server:8080
    build: ./client
    restart: always

  server:
    environment:
      - SERVER_LISTEN_URI=tcp://0.0.0.0:8080
    expose:
      - 8080
    build: ./server
    restart: always

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017